name: BanWarn
api: [3.0.0-ALPHA7]
version: 1.2.2
load: POSTWORLD
main: robske_110\BanWarn\Main
author: robske_110
website: https://github.com/robske110/BanWarn

commands:
 warn:
  description: Warnt einen Spieler
  usage: "/warn <SpielerName> <Grund> [Punkte]"
  permission: BanWarn.command.warn
 warninfo:
  description: Gibt Infos über die Warnungspunkte eines Spielers und die Gründe
  usage: "/warninfo <SpielerName>"
  permission: BanWarn.command.warninfo
  aliases: [wi, warni, winfo]
 warnpardon:
  description: Löscht alle Warnungen eines Spielers oder entfernt einzelne
  usage: "/warnpardon <PlayerName>"
  permission: BanWarn.command.warnpardon
  aliases: [warnp, wpardon]

permissions:
 BanWarn.command.warn:
  description: "Erlaubt die benutzung des /warn Kommandos"
  default: op
 BanWarn.command.warninfo:
  description: "Erlaubt die benutzung des /warninfo Kommandos"
  default: op
 BanWarn.command.warnpardon:
  description: "Erlaubt die benutzung des /warnpardon Kommandos"
  default: op
