name: BanWarn
api: [1.13.0, 2.0.0]
version: 1.2.1-InDev
load: POSTWORLD
main: robske_110\BanWarn\Main
author: robske_110
website: https://github.com/robske110/BanWarn

commands:
 warn:
  description: Warnt einen Spieler
  usage: "/warn <SpielerName> <Grund> [Punkte]"
  permission: BanWarn.command.warn
 warninfo:
  description: Gibt Infos über die Warnungspunkte eines Spielers und die Gründe
  usage: "/warninfo <SpielerName>"
  permission: BanWarn.command.warninfo
  aliases: [wi, warni]
 warnpardon:
  description: Löscht alle Warnungen eines Spielers oder entfernt einzelne
  usage: "/warnpardon <PlayerName>"
  permission: BanWarn.command.warnpardon
  aliases: [warnp, wpardon]

permissions:
 BanWarn.command.warn:
  description: "Erlaubt die benutzung des /warn Kommandos"
  default: op
 BanWarn.command.warninfo:
  description: "Erlaubt die benutzung des /warninfo Kommandos"
  default: op
 BanWarn.command.warnpardon:
  description: "Erlaubt die benutzung des /warnpardon Kommandos"
  default: op
